# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-b7eefc8a-8771-4c22-89af-ca36d772ea19";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-b7eefc8a-8771-4c22-89af-ca36d772ea19".device = "/dev/disk/by-uuid/b7eefc8a-8771-4c22-89af-ca36d772ea19";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D4A2-32E9";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-28c06527-3ee0-41dd-9b18-149d624dbd97";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
